apiVersion: apps/v1
kind: Deployment
metadata:
  name: c4c-address-verification
  labels:
    app: c4c-address-verification
    version: v1
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: c4c-address-verification
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: c4c-address-verification
        version: v1

    spec:
      imagePullSecrets:
        - name: regsecret

      containers:
      - name: c4c-address-verification
        image: ticid.docker.repositories.sap.ondemand.com/uc/c4c-address-verification:0.0.7
        imagePullPolicy: Always

        env:
        - name: PORT
          value: "8080"

        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: c4c-address-verification-secret
              key: GOOGLE_API_KEY

        ports:
          - containerPort: 8080
            protocol: TCP
            name: http

        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"

        readinessProbe:
          failureThreshold: 2
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          timeoutSeconds: 8

        livenessProbe:
          failureThreshold: 4
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          timeoutSeconds: 8

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10

