---
apiVersion: v1
kind: Service
metadata:
  name: c4c-address-verification
  labels:
    app: c4c-address-verification
    service: c4c-address-verification
spec:
  type: ClusterIP
  #ClusterIP: None   # for Headless Services
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: c4c-address-verification
